### ISSUE TITLE
Support Fastify v5

### ISSUE THREAD

**Issue by michalsanger** [smartiniOnGitHub/fastify-healthcheck#24]
After upgrade to `"fastify": "5.0.0"` I'm getting this error:
```
FastifyError [Error]: fastify-plugin: @fastify/under-pressure - expected '4.x' fastify version, '5.0.0' is installed
    at Object.checkVersion (/home/node/app/node_modules/fastify/lib/pluginUtils.js:125:11)
    at Object.registerPlugin (/home/node/app/node_modules/fastify/lib/pluginUtils.js:148:16)
    at Boot.override (/home/node/app/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Boot._loadPlugin (/home/node/app/node_modules/avvio/boot.js:425:25)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}
```

**Comment by smartiniOnGitHub** [comment]
Hi, the error is because current version only supports Fastify 4.x, I need to update code for Fastify 5.x; I'll try to do ASAP but I need few days ...

**Comment by smartiniOnGitHub** [comment]
Hi, plugin release 5.0.0 just published, all should be good now with fastify 5. Bye
